### ISSUE TITLE
Admin Accept refund request and pre-loader showing continuously

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#10]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> orders
Version: 3.1.0
Description: When Admin Accept refund request the pre-loader showing continuously and not getting timeout.
Refer- https://drive.google.com/file/d/1vMhKQy0fAbdIZruMaz7mRaEUtY041JHR/view?usp=sharing

**Comment by mohammaddanish-cedcoss** [comment]
works fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
