### ISSUE TITLE
In Integration setting Save setting button is not working properly

### ISSUE THREAD

**Issue by pranjali-wps** [MakeWebBetter/WooCommerce-Refund-and-Exchange-Lite#109]
WP Ver.- 6.2.2
WC Ver.- 7.7.2
Plugin Ver.- 4.2.0
Description- When I have Click on "Save setting" button is not working properly
Steps to be followed-
Go to WPSwings --> Return Refund and Exchange for WooCommerce.
Integration settings--> Scroll down and click on "Click Here".

[scrnli_02_06_2023_15-08-37.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/e82c525f-3fd6-4729-9006-d8be4bce2df2)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed
