### ISSUE TITLE
Admin Accept refund request but status is not changing to refund approved

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#11]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> orders
Version: 3.1.0
Description: When Admin Accept refund request the order status is not changing to **Refund Approved**.
![Screenshot12](https://user-images.githubusercontent.com/76723329/112429810-337c6080-8d63-11eb-8bd4-b078a273eaf2.png)
![Screenshot13](https://user-images.githubusercontent.com/76723329/112429882-5575e300-8d63-11eb-9f28-43facef54cf7.png)

**Comment by mohammaddanish-cedcoss** [comment]
works fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
