### ISSUE TITLE
RMA Lite Setting Overview page header in mobile view.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#12]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Refund-Exchange Lite --> Overview
Version: 3.1.0
Description: On the RMA Lite Setting Overview page the header UI should be improved in responsive mode.
![Screenshot14](https://user-images.githubusercontent.com/76723329/112442418-cd4b0a00-8d71-11eb-994a-7f6b943c1958.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
