### ISSUE TITLE
Plugin name should be Return Refund and Exchange for WooCommerce

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#13]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> Plugins --> Return Refund and Exchange for Woocommerce
Version: 3.1.0
Description: The Plugin name should be "Return Refund and Exchange for **WooCommerce**".

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented.
