### ISSUE TITLE
If Refund button will not be shown for some order statuses they should not be available for admin to select.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#14]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Refund-Exchange Lite --> Refund Products --> Select the orderstatus in which the order can be Refunded
Version: 3.1.0
Description: If Refund button will not be shown for some order statuses they should not be available for admin to select.
![Screenshot15](https://user-images.githubusercontent.com/76723329/112448985-f4f1a080-8d78-11eb-8ca7-be76e4174a9d.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
