### ISSUE TITLE
"Enter number Of Attachment to be send" field validation

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#15]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Refund-Exchange Lite
Version: 3.1.0
Description: The "Enter number Of Attachment to be send" field should not accept negative numeric values as input, it is creating issue on store.
![Screenshot16](https://user-images.githubusercontent.com/76723329/112453002-3dab5880-8d7d-11eb-8613-860aa0cf8405.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
