### ISSUE TITLE
"Enter number Of Attachment to be send" field help-tip

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#16]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Refund-Exchange Lite
Version: 3.1.0
Description: The "Enter number Of Attachment to be send" field should have a help-tip as other input fields have.
![Screenshot16](https://user-images.githubusercontent.com/76723329/112456865-2c644b00-8d81-11eb-8dec-e6338f4a6fdd.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
