### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#17]
Plugin: Return Refund and Exchange for WooCommerce
Version: 3.1.0
Description: 
**String-** "**ced_rnx_refund_upload_files**" should not get translated.

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
working fine.
