### ISSUE TITLE
Grammatical issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#18]
Plugin: Return Refund and Exchange for WooCommerce
Version: 3.1.0
Description:

**Suggessions:**
/home/cedcoss/Local Sites/oldorg/app/public/wp-content/plugins/WooCommerce-Refund-and-Exchange-Lite/admin/partials/mwb-rnx-lite-pro-purchase-template.php line: 41
--> Connect With Us and Explore More About Return Refund and Exchange for **Woocommerce** -> Connect With Us and Explore More About Return Refund and Exchange for **WooCommerce**

/home/cedcoss/Local Sites/oldorg/app/public/wp-content/plugins/WooCommerce-Refund-and-Exchange-Lite/woocommerce-refund-and-exchange-lite.php line: 389
--> WooCommerce is not activated, Please activate WooCommerce first to install WooCommerce Refund and Exchange Lite.

**Grammatical issues:**

#: admin/class-woocommerce_refund_and_exchange_lite-admin.php:109
msgid "Message has been sent succesfully"
msgstr "" --> successfully

#: admin/class-woocommerce_refund_and_exchange_lite-admin.php:675
msgid "User Request of Refund Product is approevd"
msgstr "" --> approved

#: admin/class-woocommerce_refund_and_exchange_lite-admin.php:731
msgid "Product Stock is updated Succesfully."
msgstr "" --> Successfully

#: admin/partials/mwb-rnx-lite-notification.php:248
msgid ""
"These are some shortcodes that you can use in EMAIL MESSESGES. It will be "
"changed with its dynamic values."
msgstr "" --> MESSAGES

#: admin/partials/mwb-rnx-lite-notification.php:273
msgid "Recieved Refund Request Message"
msgstr "" --> Received

#: admin/partials/mwb-rnx-lite-order-msg-history-meta.php:27
#: public/partials/mwb-rnx-lite-view-order-msg.php:70
msgid "Messages Refreshed Succesfully."
msgstr "" --> Successfully

#: admin/partials/mwb-rnx-lite-return-product-meta.php:229
msgid "Following product refund request is cancelled on"
msgstr "" --> canceled

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:239
msgid ""
"If days exceeds from the day of order placed then Refund Request will not be "
"send. If value is 0 or blank then Refund button will not visible at order "
"detail page."
msgstr ""
--> "If days exceeds from the day of order placed then Refund Request will not be "
"send. If the value is 0 or blank then the Refund button will not visible at order "
"detail page."

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:253
msgid "Enter number Of Attachment to be send"
msgstr "" 
--> "Enter number Of Attachment to send"

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:254
msgid "Enter the number of attachment cusomter can add one time during refund."
msgstr "" --> attachments, customer

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:263
msgid "Enable this for user to send the detail description of Refund request."
msgstr "" --> the user

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:270
msgid "Enable this to increase product stock when Refund request is accepted."
msgstr "" --> the Refund

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:276
msgid "Select the orderstatus in which the order can be Refunded"
msgstr "" --> order status

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:296
msgid ""
"Custom Refund Rules Editor (HTML and CSS allowed).Put your custom Refund "
"rules here."
msgstr ""
--> "Custom Refund Rules Editor (HTML and CSS allowed). Put your custom Refund "
"rules here."

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:320
msgid ""
"Enable this if you want to allow your customers to upload attachment along "
"with their order related messages."
msgstr "" --> order-related

#: public/class-woocommerce_refund_and_exchange_lite-public.php:371
msgid ""
"Your Giftcard have been expired so we you can not proceed for refund . Thanks"
msgstr ""
--> "Your Giftcard has been expired so you can not proceed with the refund. Thanks"

#: public/class-woocommerce_refund_and_exchange_lite-public.php:380
msgid ""
"Your  Giftcard have been used so we you can not proceed for refund . Thanks"
msgstr ""
--> "Your  Giftcard has been used so you can not proceed with the refund. Thanks"

#: public/class-woocommerce_refund_and_exchange_lite-public.php:700
msgid ""
"Message send successfully.You have received a notification mail regarding "
"this, Please check your mail. Soon You redirect to My Account Page. Thanks"
msgstr ""
--> "Message send successfully. You have received a notification mail regarding "
"this, Please check your mail. Soon You redirect to the My Account Page. Thanks"

#: public/class-woocommerce_refund_and_exchange_lite-public.php:933
msgid "Above product Refund request is cancelled on"
msgstr "" --> canceled

#: woocommerce-refund-and-exchange-lite.php:408
msgid ""
"WooCommerce RMA | Return-Refund-Exchange is activated so you did not need to "
"install WooCommerce Refund and Exchange Lite because Main version is "
"contains all the feature of our lite extention ."
msgstr ""
--> "WooCommerce RMA | Return-Refund-Exchange is activated so you did not need to "
"install WooCommerce Refund and Exchange Lite because the Main version is "
"contains all the features of our lite extension ."

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
**Still pending:**
#: admin/partials/mwb-rnx-lite-order-msg-history-meta.php:27
#: public/partials/mwb-rnx-lite-view-order-msg.php:70
msgid "Messages Refreshed Succesfully."
msgstr "" --> Successfully

#: admin/settings/class-woocommerce_refund_and_exchange_lite-settings.php:253
msgid "Enter number Of Attachment to be send"
msgstr ""
--> "Enter number Of Attachment to send"

#: public/class-woocommerce_refund_and_exchange_lite-public.php:371
msgid ""
"Your Giftcard have been expired so we you can not proceed for refund . Thanks"
msgstr ""
--> "Your Giftcard has been expired so you can not proceed with the refund. Thanks"

#: public/class-woocommerce_refund_and_exchange_lite-public.php:380
msgid ""
"Your Giftcard have been used so we you can not proceed for refund . Thanks"
msgstr ""
--> "Your Giftcard has been used so you can not proceed with the refund. Thanks"

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
