### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#19]
Plugin: Return Refund and Exchange for WooCommerce
Version: 3.1.0
Description:

Refer: 
**QA issues:-** [Return Refund and Exchange for WooCommerce QA issues.docx](https://github.com/Makewebbetter/WooCommerce-Refund-and-Exchange-Lite/files/6243927/Return.Refund.and.Exchange.for.WooCommerce.QA.issues.docx)
**phpcs/wpcs issues:-** [WooCommerce-Refund-and-Exchange-Lite.docx](https://github.com/Makewebbetter/WooCommerce-Refund-and-Exchange-Lite/files/6243935/WooCommerce-Refund-and-Exchange-Lite.docx)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
