### ISSUE TITLE
Issue in the Refund --> Predefined Refund Reason input field, while using word with apostrophe 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#23]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Plugin --> RETURN REFUND AND EXCHANGE FOR WOOCOMMERCE --> Refund 
Version: 4.0.0
Description: If we add words with apostrophe ( ' ) is reflects some problem while deleting or editing it. 

![image](https://user-images.githubusercontent.com/85384857/128896304-a731e61a-7865-42b9-9991-c38a1c73844a.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
