### ISSUE TITLE
Message shown after Refund Request is placed

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#24]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Shop
Version: 4.0.0
Description: After the refund request is submitted it will be better if the message could show the "**Refund request placed successfully, You will receive a notification mail regarding this** ".
![image](https://user-images.githubusercontent.com/85384857/128900957-4d264dbe-11ac-4c5c-9001-b6d79db4f5ba.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
