### ISSUE TITLE
While cancelling the refund request, the loader is taking too much time 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#25]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Admin Panel --> WooCommerce --> Orders
Version: 4.0.0
Description: If we are canceling the refund request, the loader is taking too much  time
![image](https://user-images.githubusercontent.com/85384857/128902791-a99a2a01-2bc3-499c-8e4e-65a7febeac7c.png)

**Comment by mohammaddanish-cedcoss** [comment]
https://drive.google.com/file/d/1uVAi1BsoI7EOqMOK4csWVB2qb8ZYQb_g/view?usp=sharing

**Comment by Sukirti-CEDCOSS** [comment]
Verified
