### ISSUE TITLE
The attachment with a message is reflecting an error  

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#26]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Admin Panel --> WooCommerce --> Orders
Version: 4.0.0
Description: The attachment with a message is reflecting an error  
![image](https://user-images.githubusercontent.com/85384857/128909493-11548268-142e-4140-88f3-8929721affef.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
