### ISSUE TITLE
Design issue on button on My account-->Orders

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#27]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Shop --> Orders
Version: 4.0.0
Description: Design issue on button on My account-->Orders
![image](https://user-images.githubusercontent.com/85384857/129915395-ce3d8500-4e8e-4646-a8f6-8b63d3dd2c90.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
