### ISSUE TITLE
Wherever there is a  option to upload files, please specify that only images to be uploaded

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#28]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Shop --> Orders --> Order Message
Version: 4.0.0
Description: Wherever there is an option to upload files, please specify that only images to be uploaded
![image](https://user-images.githubusercontent.com/85384857/129916402-bacf7fc5-9017-401c-a281-8ee15172d7c6.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
