### ISSUE TITLE
Update Overview page 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#30]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Plugin --> RETURN REFUND AND EXCHANGE FOR WOOCOMMERCE --> Overview
Version: 4.0.0
Description: Update Overview page 
![image](https://user-images.githubusercontent.com/85384857/129917519-60316e2c-3a30-4cdf-9a4c-23814fffaa30.png)

**Comment by mohammaddanish-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
