### ISSUE TITLE
Design Issue 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#31]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Shop --> Order --> Order Messages
Version: 4.0.0
Description: Design Issue with different themes, i, e. Divi, Avada, Twenty Twenty-One
![image](https://user-images.githubusercontent.com/85384857/129920783-06f5679f-eecf-42b3-ab0c-27b1b94d90c5.png)
![image](https://user-images.githubusercontent.com/85384857/129920807-b5f23903-f04c-4e4c-b856-ddd146b1f6c9.png)
![image](https://user-images.githubusercontent.com/85384857/129920829-44e47356-c169-4ae9-a1c7-346231baf09e.png)
![image](https://user-images.githubusercontent.com/85384857/129920841-e3dad6b5-2db0-4f21-8bcb-b4d9dd8a5c8c.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified

**Comment by Sukirti-CEDCOSS** [comment]
Verified
