### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#32]
DOC:
https://docs.google.com/document/d/1q2CWUgSlG_ZN_mTzdV86tzwr0wNoKN4zrXZE_As5Yyk/edit?usp=sharing

File:
[PHPcs.zip](https://github.com/Makewebbetter/WooCommerce-Refund-and-Exchange-Lite/files/7454183/PHPcs.zip)
[WooCommerce-Refund-and-Exchange-Lite.zip](https://github.com/Makewebbetter/WooCommerce-Refund-and-Exchange-Lite/files/7454184/WooCommerce-Refund-and-Exchange-Lite.zip)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
