### ISSUE TITLE
View Order Messages page Attach Files/ Choose files text

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#7]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Store-end --> My account --> View order Messages
Version: 3.1.0
Description: On the View Order Messages page the  Attach Files/ Choose files text is not correct as user can only attach one file at a time. The text should be Attach File/ Choose file.
![Screenshot9](https://user-images.githubusercontent.com/76723329/112423472-b51ac100-8d58-11eb-97aa-a87813b465e5.png)

**Comment by mohammaddanish-cedcoss** [comment]
User can attach more than one file at a time.

**Comment by mohammaddanish-cedcoss** [comment]
User can attach more than one file at a time.
