### ISSUE TITLE
Order Message History Attach Files/ Choose files text

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#8]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Orders --> Order Message History
Version: 3.1.0
Description: In the Order Message History block the Attach Files/ Choose files text is not correct as the admin can only attach one file at a time. The text should be Attach File/ Choose file.
![Screenshot10](https://user-images.githubusercontent.com/76723329/112423832-5f92e400-8d59-11eb-9be6-3ac37d98754a.png)

**Comment by mohammaddanish-cedcoss** [comment]
Admin can attach more than one file at a time.

**Comment by mohammaddanish-cedcoss** [comment]
Admin can attach multiple files at a time.
