### ISSUE TITLE
File attached status is not visible to user in mobile view

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/WooCommerce-Refund-and-Exchange-Lite#9]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Store-end --> My account --> View order Messages
Version: 3.1.0
Description: The status/ name of File attached by the user is not visible to the user in the mobile view after attaching the file. The user should be able to know whether the file is attached or not.
![Screenshot11](https://user-images.githubusercontent.com/76723329/112427902-61ac7100-8d60-11eb-8e0d-a8a424e1fad0.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
